### PR TITLE
Fixes for a couple of issues related to using multiple schemas

### PR DESCRIPTION
**Pull request by vault**
In my environment we have lots of tables with different schemas residing in a metadata that has yet another schema. This pull request includes the changes required to get continuum working in that scenario.

### CODE REVIEW

**Comment by kvesteri** [comment]
This looks good. Could you also add a test for this and remove the unnecessary commits?

**Comment by vault** [comment]
Added tests and fixed a few related issues I found while getting the tests to work.

**Comment by rhymoid** [comment]
Are there any plans to merge this patch? PostgreSQL's schema system makes life so much easier, and it would really help if sqlalchemy-continuum could work with it.

**Comment by kvesteri** [comment]
Thanks for the PR! :train:

**Comment by kvesteri** [comment]
Relased as part of 1.3.2

**Pull request merged**
