### PR TITLE
don't include excluded properties

### LINKED ISSUE #152: Unable to exclude many-to-many relationships
This seems to be a bit different from the other many-to-many issues here: I have a many-to-many relationship on a versioned table that I don't want tracked by continuum.

Here's a paired down version of the models:

```
from sqlalchemy import Table, Column, DateTime, String, Integer, ForeignKey, Text, func
from sqlalchemy.orm import relationship, backref

from meta import Base 

channel_tag = Table('service_channel_service_tag', Base.metadata,
    Column('channel_id', Integer, ForeignKey('service_channel.id'), primary_key=True),
    Column('tag_id', Integer, ForeignKey('service_tag.id'))
)

class ServiceChannel(Base):
    __tablename__ = 'service_channel'
    __versioned__ = {
        'exclude': ['tags']
    }

    id = Column(Integer, primary_key=True)
    title = Column(Text(convert_unicode=True))
    description = Column(Text(convert_unicode=True))

    tags = relationship("ServiceTag",
                        secondary=channel_tag,
                        backref="channels")

    def __repr__(self):
        return "<ServiceChannel(id='%s')>" % (self.id)

class ServiceTag(Base):
    __tablename__ = 'service_tag'

    id = Column(Integer, primary_key=True)
    tag = Column(String(30), unique=True, nullable=False)

    def __repr__(self):
        return "<ServiceTag(id='%s', tag='%s')>" % (self.id, self.tag)
```

In this particular case, having the historical data of tags is unnecessary. Is there some obvious way to have continuum ignore this that I'm missing?

### PR DESCRIPTION
**Pull request by fuhrysteve**
Hi @kvesteri! I think this should fix #152 - it seems to for me. Wondering if you could take a look?

### CODE REVIEW

**Comment by fuhrysteve** [comment]
In a nutshell, this makes items in `__versioned__['exclude']` honor many to many relationships, and not just columns.

**Comment by kvesteri** [comment]
Thanks for the PR. Before merging this needs tests

**Comment by fpruitt** [comment]
@kvesteri @fuhrysteve I can confirm that this fixes #152 (an issue I spent several hours debugging today).. I'll look into providing a test to get this ready to merge later on tonight.

**Comment by fuhrysteve** [comment]
@fpruitt that would be awesome! Sorry I haven't circled back to write tests myself

**Comment by fuhrysteve** [comment]
@kvesteri added some tests!

**Comment by fpruitt** [comment]
Until this is merged, my company is installing from this commit (in case there is a delay getting this merged)

https://github.com/fpruitt/sqlalchemy-continuum/commit/4d850b6d39a104d99f7379aba63656376897fec7

**Comment by fuhrysteve** [comment]
Removed the commit where I tried (and failed) to fix some weirdness with the build failing due to a problem w/ mysql on travisci - it appears to be fixed upstream now.

Additionally, I added python 3.6 (and removed 3.3) from the build and `setup.py`

@kvesteri - let me know if there's anything else I can do to polish this up - Thanks!

**Comment by vincentwhales** [comment]
Please merge this, thank you.

**Comment by kvesteri** [comment]
Thanks for the PR! :train:

**Pull request merged**
