### PR TITLE
Fix SAWarning for scalar_subquery warning SQLA<1.4

### PR DESCRIPTION
**Pull request by indiVar0508**
Attempt to fix all the scalar_subquery warning identified in this [action_job run](https://github.com/kvesteri/sqlalchemy-continuum/runs/8106322990?check_suite_focus=true) as part of #263 , used same sol used in #269  by @TomGoBravo 

Pytest run on Master: `345 failed, 309 passed, 14 skipped, 302 warnings, 90 errors`
Pytest run after changes: `345 failed, 309 passed, 14 skipped, 238 warnings, 90 errors`

### CODE REVIEW

**Comment by indiVar0508** [comment]
Hi @marksteward ,

can you review this PR and trigger Travis Build for this one also?

**Comment by indiVar0508** [comment]
Hi @marksteward ,

The last [Job run](https://github.com/kvesteri/sqlalchemy-continuum/runs/8118630919?check_suite_focus=true) failed it seems due to [FROM clause subquery](https://github.com/kvesteri/sqlalchemy-continuum/runs/8118630919?check_suite_focus=true) i have added a fix for that in this [commit](https://github.com/kvesteri/sqlalchemy-continuum/pull/300/commits/a2981a132bb17e294d02affaa8eebbf1adf843f8), and tested in my local with SQLA >1.4 and <1.4 with mysql server for `tests/test_accessors.py` and it seems to work.

Could you review and re-trigger the travis CI Build ?

**Comment by indiVar0508** [comment]
Splitting this PR into 5 seperate PR(s) to allow fix for warning(s) which are not causing any issue

**Comment by indiVar0508** [comment]
Hi @marksteward ,

Could also trigger Travis Build for this one

**Comment by indiVar0508** [comment]
Hey, 

Not sure, but travis build is showing failed for this one some checkout task failed is it ok ?

**Comment by marksteward** [comment]
Yeah, it cancelled the run because I merged it. The main branch is passing fine.

**Pull request merged**
