### PR TITLE
Fix of issue #105

### PR DESCRIPTION
**Pull request by piotr-dobrogost**
Rough idea of how to deal with error in issue #105. I'm not sure it's correct – please review carefully.

### CODE REVIEW

**Comment by filwaitman** [comment]
I've just smoke-tested this PR. Well, the error has changed.  :smile: 

The code I've used for testing is below:
```
#-*- coding: utf-8 -*-
from datetime import datetime

from sqlalchemy import Column, DateTime, Integer, String, create_engine, ForeignKey
from sqlalchemy.orm import create_session, backref, relationship
from sqlalchemy.ext.declarative import declarative_base

e = create_engine('sqlite:////tmp/whatever.db', echo=True)
Base = declarative_base(bind=e)


from sqlalchemy_continuum import make_versioned
make_versioned(user_cls=None)


def return_now():
    return datetime.utcnow()


class Car(Base):
    __tablename__ = 'cars'
    # __versioned__ = {'include': ['created', 'updated']}

    id = Column(Integer, primary_key=True)
    name = Column(String(50))
    created = Column(DateTime, default=return_now, index=True)
    updated = Column(DateTime, default=return_now, onupdate=return_now, index=True)


class Employee(Base):
    __tablename__ = 'employees'
    __versioned__ = {'include': ['created', 'updated']}

    employee_id = Column(Integer, primary_key=True)
    name = Column(String(50))
    type = Column(String(30), nullable=False)

    car_id = Column(Integer, ForeignKey('cars.id'), index=True)
    car = relationship('Car', backref=backref('employees', uselist=False), foreign_keys=[car_id])

    created = Column(DateTime, default=return_now, index=True)
    updated = Column(DateTime, default=return_now, onupdate=return_now, index=True)

    __mapper_args__ = {'polymorphic_on': type}

    def __init__(self, name):
        self.name = name


class Manager(Employee):
    __tablename__ = 'managers'
    __mapper_args__ = {'polymorphic_identity': 'manager'}

    employee_id = Column(Integer, ForeignKey('employees.employee_id'), primary_key=True)
    manager_data = Column(String(50))

    def __init__(self, name, manager_data):
        super(Manager, self).__init__(name)
        self.manager_data = manager_data


class Owner(Manager):
    __tablename__ = 'owners'
    __mapper_args__ = {'polymorphic_identity': 'owner'}

    employee_id = Column(Integer, ForeignKey('managers.employee_id'), primary_key=True)
    owner_secret = Column(String(50))

    def __init__(self, name, manager_data, owner_secret):
        super(Owner, self).__init__(name, manager_data)
        self.owner_secret = owner_secret


Base.metadata.drop_all()
Base.metadata.create_all()

s = create_session(bind=e, autoflush=True, autocommit=False)
o = Owner('nosklo', 'mgr001', 'ownerpwd')
s.add(o)
s.commit()
```

And now the error I got was:
```

# [...] crazy stuff here

Traceback (most recent call last):
  File "continuum_bug.py", line 80, in <module>
    s.commit()
  File "/home/waitman/.virtualenvs/alchemypiotr/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 790, in commit
    self.transaction.commit()
  File "/home/waitman/.virtualenvs/alchemypiotr/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 392, in commit
    self._prepare_impl()
  File "/home/waitman/.virtualenvs/alchemypiotr/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 372, in _prepare_impl
    self.session.flush()
  File "/home/waitman/.virtualenvs/alchemypiotr/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2004, in flush
    self._flush(objects)
  File "/home/waitman/.virtualenvs/alchemypiotr/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2031, in _flush
    self.dispatch.before_flush(self, flush_context, objects)
  File "/home/waitman/.virtualenvs/alchemypiotr/local/lib/python2.7/site-packages/sqlalchemy/event/attr.py", line 218, in __call__
    fn(*args, **kw)
  File "/home/waitman/.virtualenvs/alchemypiotr/src/sqlalchemy-continuum/sqlalchemy_continuum/manager.py", line 327, in before_flush
    uow.process_before_flush(session)
  File "/home/waitman/.virtualenvs/alchemypiotr/src/sqlalchemy-continuum/sqlalchemy_continuum/unit_of_work.py", line 71, in process_before_flush
    self.create_transaction(session)
  File "/home/waitman/.virtualenvs/alchemypiotr/src/sqlalchemy-continuum/sqlalchemy_continuum/unit_of_work.py", line 121, in create_transaction
    self.version_session.flush()
  File "/home/waitman/.virtualenvs/alchemypiotr/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2004, in flush
    self._flush(objects)
  File "/home/waitman/.virtualenvs/alchemypiotr/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2122, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/waitman/.virtualenvs/alchemypiotr/local/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/waitman/.virtualenvs/alchemypiotr/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2086, in _flush
    flush_context.execute()
  File "/home/waitman/.virtualenvs/alchemypiotr/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 373, in execute
    rec.execute(self)
  File "/home/waitman/.virtualenvs/alchemypiotr/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 532, in execute
    uow
  File "/home/waitman/.virtualenvs/alchemypiotr/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 174, in save_obj
    mapper, table, insert)
  File "/home/waitman/.virtualenvs/alchemypiotr/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 781, in _emit_insert_statements
    execute(statement, params)
  File "/home/waitman/.virtualenvs/alchemypiotr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/home/waitman/.virtualenvs/alchemypiotr/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/waitman/.virtualenvs/alchemypiotr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/waitman/.virtualenvs/alchemypiotr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/home/waitman/.virtualenvs/alchemypiotr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/home/waitman/.virtualenvs/alchemypiotr/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/home/waitman/.virtualenvs/alchemypiotr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/home/waitman/.virtualenvs/alchemypiotr/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: transaction [SQL: u'INSERT INTO "transaction" (issued_at, remote_addr) VALUES (?, ?)'] [parameters: ('2015-09-23 18:27:48.109895', None)]
```

**Comment by filwaitman** [comment]
I've just tested it. Worked for me!  :smiley: 

Follows the scenario I have:
```
#-*- coding: utf-8 -*-
from datetime import datetime

from sqlalchemy import Column, DateTime, Integer, String, create_engine, ForeignKey, orm
from sqlalchemy.orm import create_session, backref, relationship
from sqlalchemy.ext.declarative import declarative_base

e = create_engine('sqlite:////tmp/whatever2.db', echo=True)
Base = declarative_base(bind=e)


from sqlalchemy_continuum import make_versioned
make_versioned(user_cls=None)


def return_now():
    return datetime.utcnow()


class Car(Base):
    __tablename__ = 'cars'

    id = Column(Integer, primary_key=True)
    name = Column(String(50))
    created = Column(DateTime, default=return_now, index=True)
    updated = Column(DateTime, default=return_now, onupdate=return_now, index=True)


class Employee(Base):
    __tablename__ = 'employees'
    __versioned__ = {'include': ['created', 'updated']}

    employee_id = Column(Integer, primary_key=True)
    name = Column(String(50))
    type = Column(String(30), nullable=False)

    car_id = Column(Integer, ForeignKey('cars.id'), index=True)
    car = relationship('Car', backref=backref('employees', uselist=False), foreign_keys=[car_id])

    created = Column(DateTime, default=return_now, index=True)
    updated = Column(DateTime, default=return_now, onupdate=return_now, index=True)

    __mapper_args__ = {'polymorphic_on': type}

    def __init__(self, name):
        self.name = name


class Manager(Employee):
    __tablename__ = 'managers'
    __mapper_args__ = {'polymorphic_identity': 'manager'}
    # __versioned__ = {'include': ['created', 'updated']}

    employee_id = Column(Integer, ForeignKey('employees.employee_id'), primary_key=True)
    manager_data = Column(String(50))

    def __init__(self, name, manager_data):
        super(Manager, self).__init__(name)
        self.manager_data = manager_data


class Owner(Manager):
    __tablename__ = 'owners'
    __mapper_args__ = {'polymorphic_identity': 'owner'}
    __versioned__ = {'include': ['created', 'updated']}

    employee_id = Column(Integer, ForeignKey('managers.employee_id'), primary_key=True)
    owner_secret = Column(String(50))

    def __init__(self, name, manager_data, owner_secret):
        super(Owner, self).__init__(name, manager_data)
        self.owner_secret = owner_secret


orm.configure_mappers()

Base.metadata.drop_all()
Base.metadata.create_all()

s = create_session(bind=e, autoflush=True, autocommit=False)
o = Owner('nosklo', 'asda', 'asdas')
s.add(o)
s.commit()
```

Thanks @piotr-dobrogost!  =)

**Comment by kvesteri** [comment]
Merged this manually, thanks for the PR! :train:

**Comment by piotr-dobrogost** [comment]
Did you take a look before merging? Do you think it's the right way to fix this?

**Pull request closed without merging**
